// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/shirasakaren/terraform-provider-biznetgio/internal/biznetgio"
)

var (
	_ resource.Resource                = &GpuKeypairResource{}
	_ resource.ResourceWithImportState = &GpuKeypairResource{}
)

type GpuKeypairResource struct {
	client *biznetgio.Client
}

type GpuKeypairResourceModel struct {
	ID         types.String `tfsdk:"id"`
	Name       types.String `tfsdk:"name"`
	PublicKey  types.String `tfsdk:"public_key"`
	PrivateKey types.String `tfsdk:"private_key"`
}

func (r *GpuKeypairResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "biznetgio_gpu_keypair"
}

func (r *GpuKeypairResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "GPU SSH keypair. The key material is generated by BiznetGIO; the private key is only returned once at creation.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "Keypair id.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				MarkdownDescription: "Keypair name. Changing it replaces the keypair.",
			},
			"public_key": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "Generated public key.",
			},
			"private_key": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "Generated private key, shown only once. If the API does not return it, only the portal can show it.",
			},
		},
	}
}

func (r *GpuKeypairResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*biznetgio.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *biznetgio.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *GpuKeypairResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data GpuKeypairResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	m, err := r.client.GPU().KeypairCreate(ctx, biznetgio.KeypairCreateRequest{Name: data.Name.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("unable to create gpu keypair: %s", err))
		return
	}

	keypairID, ok := gpuInt64(m, "keypair_id", "id")
	if !ok {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("gpu keypair create response missing keypair_id: %v", m))
		return
	}
	data.ID = types.StringValue(strconv.FormatInt(keypairID, 10))
	gpuKeypairSetFromMap(&data, m)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *GpuKeypairResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data GpuKeypairResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	keypairID, err := strconv.ParseInt(data.ID.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("invalid gpu keypair id %q: %s", data.ID.ValueString(), err))
		return
	}

	items, err := r.client.GPU().KeypairList(ctx)
	if err != nil {
		if biznetgio.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("unable to list gpu keypairs: %s", err))
		return
	}

	var found map[string]any
	for _, it := range items {
		if id, ok := gpuInt64(it, "keypair_id", "id"); ok && id == keypairID {
			found = it
			break
		}
	}
	if found == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	gpuKeypairSetFromMap(&data, found)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// no update endpoint - semua input RequiresReplace, jadi no-op aja.
func (r *GpuKeypairResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data GpuKeypairResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *GpuKeypairResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data GpuKeypairResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	keypairID, err := strconv.ParseInt(data.ID.ValueString(), 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("invalid gpu keypair id %q: %s", data.ID.ValueString(), err))
		return
	}

	if err := r.client.GPU().KeypairDelete(ctx, keypairID); err != nil && !biznetgio.IsNotFound(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("unable to delete gpu keypair %d: %s", keypairID, err))
	}
}

func (r *GpuKeypairResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func gpuKeypairSetFromMap(data *GpuKeypairResourceModel, m map[string]any) {
	if v, ok := gpuString(m, "name"); ok {
		data.Name = types.StringValue(v)
	}
	if v, ok := gpuString(m, "public_key", "pubkey"); ok {
		data.PublicKey = types.StringValue(v)
	}
	if v, ok := gpuString(m, "private_key", "private", "secret_key", "pem"); ok {
		data.PrivateKey = types.StringValue(v)
	}
}

func NewGpuKeypairResource() resource.Resource {
	return &GpuKeypairResource{}
}
